version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/UTC"
    groups:
      npm-patch-updates:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "patch"

  - package-ecosystem: "cargo"
    directory: "/contracts"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/UTC"
    groups:
      contracts-cargo-patch-updates:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "patch"

  - package-ecosystem: "cargo"
    directory: "/sdk/rust"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/UTC"
    groups:
      rust-sdk-cargo-patch-updates:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "patch"

  - package-ecosystem: "cargo"
    directory: "/services/signer"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/UTC"
    groups:
      signer-cargo-patch-updates:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "patch"

  - package-ecosystem: "cargo"
    directory: "/zk"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/UTC"
    groups:
      zk-cargo-patch-updates:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "patch"

  - package-ecosystem: "pip"
    directory: "/python"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/UTC"
    groups:
      python-patch-updates:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/UTC"
    groups:
      github-actions-patch-updates:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "patch"
